/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cooperpellaton' at '9/7/17 9:03 PM' with Gradle 2.10
 *
 * @author cooperpellaton, @date 9/7/17 9:03 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
